### ISSUE TITLE
ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-2.96 GB) is less than -17% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).

### ISSUE THREAD

**Issue by dimasaenko** [TinkeringCode/Deep-CFR#4]
python paper_experiment_sdcfr_vs_deepcfr_h2h.py
 ************************** Initing args for:  EXPERIMENT_SD-CFR_vs_Deep-CFR_FHP   **************************
Running with  20 LearnerActor Workers.
Traceback (most recent call last):
  File "paper_experiment_sdcfr_vs_deepcfr_h2h.py", line 75, in <module>
    n_iterations=150,
  File "/Users/d.saienko/Data Science/Deep-CFR/DeepCFR/workers/driver/Driver.py", line 21, in __init__
    chief_cls=Chief, eval_agent_cls=EvalAgentDeepCFR)
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/PokerRL/rl/base_cls/workers/DriverBase.py", line 35, in __init__
    self._ray.init_local()
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/PokerRL/rl/MaybeRay.py", line 44, in init_local
    object_store_memory=min(2 * (10 ** 10), int(psutil.virtual_memory().total * 0.4)),
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1323, in init
    head=True, shutdown_at_exit=False, ray_params=ray_params)
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/node.py", line 149, in __init__
    self.start_head_processes()
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/node.py", line 571, in start_head_processes
    self.start_redis()
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/node.py", line 419, in start_redis
    self.get_resource_spec(),
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/node.py", line 240, in get_resource_spec
    self._ray_params.redis_max_memory).resolve(is_head=self.head)
  File "/Users/d.saienko/anaconda3/lib/python3.7/site-packages/ray/resource_spec.py", line 195, in resolve
    int(100 * (memory / system_memory))))
ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-2.96 GB) is less than -17% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).

**Comment by dimasaenko** [comment]
Is there any way to config allocated memory?

**Comment by dimasaenko** [comment]
It can be fixed due to cloning repository of PokerRL and edit file PokerRL/rl/MaybeRay.py
